require("senthil1216.plugins-setup")
require("senthil1216.core.options")
require("senthil1216.core.colorscheme")
require("senthil1216.core.keymaps")
require("senthil1216.plugins.nvim-tree")
require("senthil1216.plugins.lualine")
require("senthil1216.plugins.telescope")
require("senthil1216.plugins.nvim-cmp")
require("senthil1216.plugins.lsp.mason")
require("senthil1216.plugins.lsp.lspsaga")
require("senthil1216.plugins.lsp.lspconfig")
-- require("senthil1216.plugins.bufferline")
require("senthil1216.plugins.treesitter")
require("senthil1216.plugins.gitsigns")
require("senthil1216.plugins.endwise")
require("senthil1216.plugins.indent")
require("senthil1216.plugins.barbar")
require("senthil1216.plugins.autopairs")
require("senthil1216.plugins.fzf")
-- require("senthil1216.plugins.nvim-mapper")
-- require("senthil1216.plugins.telescope-filebrowser")
